image: Visual Studio 2022
install:
- ps: |
    Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
    & $env:temp\dotnet-install.ps1 -Architecture x64 -Version '9.0.100' -InstallDir "$env:ProgramFiles\dotnet"
build_script:
  - cmd: dotnet build --configuration Release -p:ContinuousIntegrationBuild=true
test:
  assemblies:
    only:
      - '**\*.Tests.dll'
test_script:
  - dotnet test --configuration Release --no-build --no-restore
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
artifacts:
  - path: 'src\Fractions\bin\Release\*.nupkg'
    type: NuGetPackage
  - path: 'src\Fractions.Json\bin\Release\*.nupkg'
    type: NuGetPackage